### ISSUE TITLE
Raspberry Pi: TypeError: Property '32' of object #<Object> is not a function

### ISSUE THREAD

**Issue by dan-mckay** [rwaldron/johnny-five#114]
I am getting this error when trying to write to an LCD through an Arduino that is connected to a Raspberry Pi. The same script works fine on Ubuntu 12.10. Any suggestions?

incidentally, the Property '32' can also change to '64 and '48' on occasion. I am stumped by it. : (   Any help would be greatly appreciated.

/home/pi/PiJukebox/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:337
                        MIDI_RESPONSE[cmd](board);
                                          ^
TypeError: Property '32' of object #<Object> is not a function
    at SerialPort.board.once.board.versionReceived (/home/pi/PiJukebox/node_modules/johnny-five/node_modules/firmata/lib/firmata.js:337:43)
    at SerialPort.EventEmitter.emit (events.js:96:17)
    at Object.parsers.raw [as parser](/home/pi/PiJukebox/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/serialport.js:23:13)
    at options.dataCallback (/home/pi/PiJukebox/node_modules/johnny-five/node_modules/firmata/node_modules/serialport/serialport.js:90:13)
    at EventEmitter.emit (events.js:96:17)
    at ReadStream._emitData (fs.js:1368:10)
    at afterRead (fs.js:1350:10)
    at Object.wrapper [as oncomplete](fs.js:362:17)
